I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    play sound bruh
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/script.rpy", line 22, in <module>
    play sound bruh
NameError: name 'bruh' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script
    play sound bruh
  File "/usr/share/renpy/renpy/ast.py", line 2259, in execute
    self.call("execute")
  File "/usr/share/renpy/renpy/ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/usr/share/renpy/renpy/statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "/usr/share/renpy/renpy/python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/usr/share/renpy/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 22, in <module>
    play sound bruh
NameError: name 'bruh' is not defined

Linux-6.1.71-1-MANJARO-x86_64-with-glibc2.38 x86_64
Ren'Py 8.2.0.0+unofficial
Doki Doki UCSP 1.0
Sun Jan 28 11:08:07 2024
